baseURL       = "https://opulentsoftware.co.uk/"
languageCode  = "en-us"
title         = "Opulent Software | Ladywood - Birmingham | Website Designer | Software Developer | Mobile Developer"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Opulent Software | Website Designer | Software Solutions | Web & Mobile Apps"
  author = "Bait-Toyin Ajani"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project. Approximate budget. When it is needed by."
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      title  = "Business/Personal Website"
    [[params.contactForm.projectType]]
      title  = "Web Application"
    [[params.contactForm.projectType]]
      title  = "Mobile Application"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Level up your<br> Business Today"
    tagline               = "With our bespoke website designs and software solutions based in Ladywood, Birmingham"
    primary_button        = "Enquire Today!"
    primary_button_url    = "contact"
    secondary_button      = "See Our Work"
    secondary_button_url  = "portfolio"

  [params.blog]
    read_more             = "read more"
    more_works            = "Read some more of our stuff"
    enable                = true
    title                 = "Read some stuff"
    subtitle              = "Our blog has some cool words for everyone. Some of it technical and most of it just for entertainment. Have a read."

  [params.portfolio]
    enable    = true
    title     = "Our Recent Work"
    subtitle  = "Creating something that makes our clients happy is our first priority. Very close second is crafting it to Look Good & Be Useful."
    view_project = "view project"
    more_works = "See More Of Our Work"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Enquire Today!"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced?"
    secondary_button_url = "portfolio"

  [params.footer]
    qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Birmingham"
      phone   = "+447469722985"
      email   = "baittoyinajani@gmail.com"
      linkedin = "https://www.linkedin.com/in/bait-toyin-ajani-338961191/"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
