baseURL: "https://brilliant-hamster-e82879.netlify.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Opulent Software"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Opulent Software"
  description: "We specialize in providing services to design websites and web, mobile and desktop applications."
  images: 
    - "images/hero-image.png"

  logo: "images/logo1.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedIn: "https://www.linkedin.com/in/bait-toyin-ajani-338961191/"

  location:
    - "Brimingham, United Kingdom"

  contact:
    - "baittoyinajani@gmail.com"

  copyright: "© 2024 Opulent Software. All Rights Reserved"

  form:
    formId: "1FAIpQLSca_zlioeFpxxemfVrGleuULOITSxukKQQy4RqMp0PB0JYA2Q"
    name: "entry.2005620554"
    email: "entry.1045781291"
    phoneNumber: "entry.1166974658"
    message: "entry.839337160"

menus:
  main:
    - name: "Portfolio"
      url: "/#portfolio"
      weight: 1

    - name: "Blog"
      url: "/blog"
      weight: 2

  buttons:
    - name: "Contact us"
      url: "/contact"
      weight: 3
      pre: "btn btn-primary text-light"

  footer:
    - name: "Portfolio"
      url: "/#portfolio"
      weight: 1

    - name: "Blog"
      url: "/blog"
      weight: 2

taxonomies:
  series: "series"
  tags: "tags"
