baseURL: "https://brilliant-hamster-e82879.netlify.app/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Opulent Software Solutions"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Opulent Software Solutions"
  description: "We specialize in providing services to design websites and web, mobile and desktop applications."
  images: 
    - "images/hero-image.png"

  logo: "images/logo-default.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedIn: "https://www.linkedin.com/in/bait-toyin-ajani-338961191/"

  location:
    - "Brimingham, United Kingdom"

  contact:
    - "baittoyinajani@gmail.com"

  copyright: "© 2024 Opulent Software Solutions All Rights Reserved"

menus:
  main:
    - name: "Portfolio"
      url: "/#portfolio"
      weight: 1

    - name: "Blog"
      url: "/blog"
      weight: 2

  buttons:
    - name: "Contact us"
      url: "/#"
      weight: 3
      pre: "btn btn-primary text-light"

  footer:
    - name: "Portfolio"
      url: "/#portfolio"
      weight: 1

    - name: "Blog"
      url: "/blog"
      weight: 2

taxonomies:
  series: "series"
  tags: "tags"
